function [prdData, info] = predict_Ciliata_mustela(par, data, auxData)
% file generated by prt_predict

% unpack par, data, auxData
cPar = parscomp_st(par); vars_pull(par);
v2struct(par); v2struct(cPar); v2struct(data); v2struct(auxData);

% compute temperature correction factors
pars_T = T_A;
TC_tp = tempcorr(temp.tp, T_ref, pars_T);
TC_am = tempcorr(temp.am, T_ref, pars_T);
TC_Ri = tempcorr(temp.Ri, T_ref, pars_T);
TC_tL_m = tempcorr(temp.tL_m, T_ref, pars_T);
TC_tL_f = tempcorr(temp.tL_f, T_ref, pars_T);

% life cycle
pars_tj = [g; k; l_T; v_Hb; v_Hj; v_Hp];
[tau_j, tau_p, tau_b, l_j, l_p, l_b, l_i, rho_j, rho_B, info] = get_tj(pars_tj, f);

if info == 0
  prdData = []; return;
end

% puberty
L_p = L_m * l_p; % cm, structural length at puberty
t_p = (tau_p - tau_b)/ k_M/ TC_tp; % d, time since birth at puberty
Lw_p = L_p/ del_M; % cm, physical length at puberty

% ultimate
L_i = L_m * l_i; % cm, ultimate structural length
Lw_i = l_i * L_m/ del_M; % cm, ultimate physical length
pars_tm = [g; l_T; h_a/ k_M^2; s_G]; % compose parameter vector
tau_m = get_tm_s(pars_tm, f, l_b); % -, scaled mean life span
a_m = tau_m/ k_M/ TC_am; % d, mean life span

% reproduction
pars_R = [kap; kap_R; g; k_J; k_M; L_T; v; U_Hb; U_Hj; U_Hp]; % compose parameter vector
R_i = TC_Ri * reprod_rate_j(L_i, f, pars_R); % #/d, ultimate reproduction rate

% males
p_Am_m = z_m * p_M/ kap; % J/d.cm^2, {p_Am} spec assimilation flux
E_m_m = p_Am_m/ v; % J/cm^3, reserve capacity [E_m]
g_m = E_G/ (kap* E_m_m); % -, energy investment ratio
m_Em_m = y_E_V * E_m_m/ E_G; % mol/mol, reserve capacity
ome_m = m_Em_m * w_E/ w_V; % -, contribution of reserve to weight
if ~exist('v_Hpm','var'); v_Hpm = v_Hp; end; pars_tjm = [g_m k l_T v_Hb v_Hj v_Hpm];
[tau_jm, tau_pm, tau_bm, l_jm, l_pm, l_bm, l_im, rho_jm, rho_Bm] = get_tj(pars_tjm, f);
L_mm = v/ k_M/ g_m; % cm, max structural length
L_im = l_im * L_mm;  % cm, ultimate structural length
Lw_im = L_im/ del_M; % cm, ultimate physical length
pars_tpm = [g_m k l_T v_Hb v_Hpm]; % pars for males
[tau_pm, tau_bm, l_pm] = get_tp(pars_tpm, f); % - , scaled time, length
L_pm = L_mm * l_pm; % cm, structural length at puberty
Lw_pm = L_pm/ del_M; % cm, physical at puberty

% pack to output
prdData.tp = t_p;
prdData.am = a_m;
prdData.Lp = Lw_p;
prdData.Lpm = Lw_pm;
prdData.Li = Lw_i;
prdData.Ri = R_i;

% length - wet weight
LWw = (LWw(:,1) * del_M).^3 * (1 + f_LWw * ome); % g, wet weight

% time - length for males
[tau_jm, tau_pm, tau_bm, l_jm, l_pm, l_bm, l_im, rho_jm, rho_Bm] = get_tj(pars_tjm, f_tL_m);
r_Bm = TC_tL_m * rho_Bm * k_M; r_jm = TC_tL_m * rho_jm * k_M; t_jm = (tau_jm - tau_bm)/ k_M/ TC_tL_m;
L_bm = L_mm * l_bm;  L_jm = L_mm * l_jm; L_im = L_mm * l_im;
L_bj = L_bm * exp(tL_m(tL_m(:,1) < t_jm,1) * r_jm/ 3);
L_ji = L_im - (L_im - L_jm) * exp( - r_Bm * (tL_m(tL_m(:,1) >= t_jm,1) - t_jm));
tL_m = [L_bj; L_ji]/ del_M; % cm, physical length

% time - length
[tau_j, tau_p, tau_b, l_j, l_p, l_b, l_i, rho_j, rho_B] = get_tj(pars_tj, f_tL_f);
r_B = TC_tL_f * rho_B * k_M; r_j = TC_tL_f * rho_j * k_M; t_j = (tau_j - tau_b)/ k_M/ TC_tL_f;
L_b = L_m * l_b;  L_j = L_m * l_j; L_i = L_m * l_i;
L_bj = L_b * exp(tL_f(tL_f(:,1) < t_j,1) * r_j/ 3);
L_ji = L_i - (L_i - L_j) * exp( - r_B * (tL_f(tL_f(:,1) >= t_j,1) - t_j));
tL_f = [L_bj; L_ji]/ del_M; % cm, physical length

% pack to output
prdData.LWw = LWw;
prdData.tL_m = tL_m;
prdData.tL_f = tL_f;

